import './globals.css';
import React from 'react';
import AppShell from './components/AppShell/AppShell';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <body className="h-full">
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
